name: Events demo1
on: 
  pull_request:
    types:
     - opened
  push:
    branches:
      - main    
      - 'dev-*'
env:
   MONGO: firstvar   # we can define a env var at workflow level which can be used by all the jobs in a workflow level.
jobs:
  deploy:
    env:
      Mongojob pass: hello  # it will be accesseble in this job only
      Mongo username: hello2
      port: 8082
    runs-on: ubuntu-latest
    steps:
      - name: get code 
        run: actions/checkout@v3 
      - name: print output
        run: |
             echo "Mongo_username: ${{env.Mongo username}}"  # both will give the same output
             echo "Mongo_username: $Mongo username
      - name: run server
        run: npm start https://127.0.0.0:$port   # getting the env var value

        # these credentials should not be here it can be accessed by anyone therefore use secret go to secret in repo and save them there
# once they are saved in secret now they will be assigened or fetch like this
      env:
        mongopass: ${{secrets.mongo_pass}}
        mongouser: ${{secrets.mongo_user}}

# in secret we have 2 secret environment secret and repository secret for above we saved secret in repo secret
# environment secret are used for making diff env like prod load or etc and appling rules on that like env protection rules 
# for diff env we can save secret in the env secret related to it like for load we can save secret related to load inside it
# for same key diff env may have diffrent value. so first create environment in Environments to store secret
