name: output_info
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output github context
        run : echo "${{ toJSON(github)}}"
# ${{}} ---> this makes that we are trying to get some data this is not a simple line to print




# creating output in one job and using it in other job
name: Events demo1
on: 
  pull_request:
    types:
     - opened
  push:
    branches:
      - main    
      - 'dev-*'
  
  deploy:
    
    runs-on: ubuntu-latest
    outputs:   # here we are defining the output in this job.
      firstoutput:${{steps.publish.outputs.firstoutput}}   # so now we have set output for the overall job
    steps:
      - name: get code 
        run: actions/checkout@v3 
      - name: create a output
        id: publish
        run: echo "firstoutput= 1234 >> $GITHUB_OUTPUT"
      - name: print output
        run: |
             echo "Mongo_username: ${{env.Mongo username}}"  # both will give the same output
             echo "Mongo_username: $Mongo username
      - name: run server
        run: npm start https://127.0.0.0:$port   # getting the env var value

      env:
        mongopass: ${{secrets.mongo_pass}}
        mongouser: ${{secrets.mongo_user}}



jobs:
  needs: deploy # this jon needs or depended upon the deploy job
  hello:
    environment: load
    env:
      mongo user: ${{secrets.mongo_user}}  # now these values will be fetched from env secret of load
    steps:
      -  name: output content
         run: echo "{{needs.deploy.outputs.firstoutput}}"   # needs object will help to get the output defined in another job




##############################################################333
 - name: Get latest configuration revision
      id: get-revision
      run: |
        revision=$(aws mq describe-configuration \
          --configuration-id ${{ github.event.inputs.configuration_id }} \
          --query 'LatestRevision.Revision' --output text)
        echo "revision=$revision" >> $GITHUB_OUTPUT

    - name: Attach new config revision to broker
      run: |
        aws mq update-broker \
          --broker-id ${{ github.event.inputs.broker_id }} \
          --configuration id=${{ github.event.inputs.configuration_id }},revision=${{ steps.get-revision.outputs.revision }}

          ### both function are part of same job.
